package projectEuler;

public class problem2 {

	/*
	 * Each new term in the Fibonacci sequence is generated by 
	 * adding the previous two terms. By starting with 1 and 2, 
	 * the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * By considering the terms in the Fibonacci sequence whose values 
	 * do not exceed four million, find the sum of the even-valued terms.
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

		//Fibonacci Sequence
		int a = 0;
		int b = 1;
		int fibNumbers = 0;
		int sumFib = 0;
		while(fibNumbers<4000000){
			fibNumbers = a+b;
			a=b;
			b=fibNumbers;
			
			//If less than 4000000 and divisible by 2, add
			if(fibNumbers%2 == 0){
				sumFib += fibNumbers;
				System.out.println("fibNumbes = " + fibNumbers + "  sumFib = " + sumFib);
			}
		}
		System.out.println("sumFib= " + sumFib);
	}

}
